services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  web:
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 3 quant_web_project.wsgi:application    
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
   #Buldum — expose: anahtar kelimesi hâlâ duruyor ama değeri "8000:8000" yapılmış. expose sadece tek port numarası kabul eder
   # expose:
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - web

  celery:
    build: .
    restart: always
    #command: celery -A quant_web_project worker --loglevel=info
    command: celery -A quant_web_project.celery:app worker --loglevel=info

    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    restart: always
    #command: celery -A quant_web_project beat --loglevel=info
    command: celery -A quant_web_project.celery:app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
  static_volume:
  certbot_www:
  certbot_conf: