# Generated by Django 6.0.6 on 2026-06-19 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantSignalCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sembol', models.CharField(max_length=20, unique=True, verbose_name='Varlık Sembolü')),
                ('pazar', models.CharField(max_length=20, verbose_name='Pazar')),
                ('period', models.CharField(max_length=10, verbose_name='Mum Periyodu')),
                ('son_fiyat', models.FloatField(verbose_name='Son Güncel Fiyat')),
                ('degisim_24s', models.FloatField(verbose_name='Periyot Değişimi %')),
                ('atr_gucu', models.FloatField(verbose_name='Mevcut ATR Volatilitesi')),
                ('konsensüs_karari', models.CharField(max_length=20, verbose_name='Kurul Kararı (ARTIŞ/AZALIŞ)')),
                ('boga_ihtimali', models.FloatField(verbose_name='Boğa Olasılığı %')),
                ('ayi_ihtimali', models.FloatField(verbose_name='Ayı Olasılığı %')),
                ('ensemble_accuracy', models.FloatField(verbose_name='Model Tarihsel Başarısı %')),
                ('grafik_verisi_json', models.TextField(verbose_name='Grafik Listeleri JSON Küpü')),
                ('son_guncellenme', models.DateTimeField(auto_now=True, verbose_name='Son Sinyal Üretim Zamanı')),
            ],
            options={
                'verbose_name': 'Yapay Zeka Sinyal Havuzu',
                'verbose_name_plural': 'Yapay Zeka Sinyal Havuzları',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pazar', models.CharField(choices=[('KRIPTO', 'Kripto Para'), ('TR_HISSE', 'Borsa İstanbul'), ('ABD_HISSE', 'ABD Borsaları'), ('EMTIA', 'Emtia / Değerli Maden')], max_length=20, verbose_name='Pazar Alanı')),
                ('sembol', models.CharField(max_length=20, verbose_name='Varlık Sembolü (Örn: BTC-USD)')),
                ('adet', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Alınan Adet / Kontrat')),
                ('alis_fiyati', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Giriş / Alış Fiyatı')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='Yatırımcı')),
            ],
            options={
                'verbose_name': 'Portföy Kalemi',
                'verbose_name_plural': 'Portföy Cüzdanları',
                'ordering': ['-eklenme_tarihi'],
            },
        ),
    ]
