# Generated by Django 6.0.6 on 2026-06-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pazar', models.CharField(choices=[('KRIPTO', 'Kripto Para'), ('TR_HISSE', 'Borsa İstanbul'), ('ABD_HISSE', 'ABD Borsaları'), ('EMTIA', 'Emtia / Değerli Maden')], max_length=20, verbose_name='Pazar')),
                ('sembol', models.CharField(max_length=20, verbose_name='Varlık Sembolü (Örn: BTC-USD)')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Zamanı')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sırası')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Takip Listesi Öğesi',
                'verbose_name_plural': 'Takip Listeleri',
                'ordering': ['siralama', 'eklenme_tarihi'],
                'unique_together': {('user', 'pazar', 'sembol')},
            },
        ),
    ]
