# Generated by Django 6.0.6 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantsignalcache',
            name='anlik_cci',
            field=models.FloatField(default=0.0, verbose_name='Anlık CCI Değeri'),
        ),
        migrations.AddField(
            model_name='quantsignalcache',
            name='anlik_macd',
            field=models.FloatField(default=0.0, verbose_name='Anlık MACD Çizgisi'),
        ),
        migrations.AddField(
            model_name='quantsignalcache',
            name='anlik_rsi',
            field=models.FloatField(default=50.0, verbose_name='Anlık RSI Değeri'),
        ),
        migrations.AddField(
            model_name='quantsignalcache',
            name='anlik_stoch_k',
            field=models.FloatField(default=50.0, verbose_name='Anlık Stochastic %K'),
        ),
        migrations.AddField(
            model_name='quantsignalcache',
            name='anlik_wt1',
            field=models.FloatField(default=0.0, verbose_name='Anlık WaveTrend WT1'),
        ),
    ]
