# Generated by Django 6.0.6 on 2026-07-04 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0002_watchlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonelikPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('ucretsiz', 'Ücretsiz'), ('aylik', 'Aylık'), ('yillik', 'Yıllık')], max_length=20, unique=True, verbose_name='Plan Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat_tl', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fiyat (TL)')),
                ('sure_gun', models.PositiveIntegerField(default=0, verbose_name='Süre (Gün, 0=Sınırsız)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Abonelik Planı',
                'verbose_name_plural': 'Abonelik Planları',
            },
        ),
        migrations.CreateModel(
            name='SiteAyari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucretli_kayit_aktif', models.BooleanField(default=False, help_text='Kapalı: herkes ücretsiz kayıt olabilir. Açık: kayıtta plan seçimi ve ödeme istenir.', verbose_name='Ücretli Kayıt Aktif')),
                ('ucretsiz_gunluk_analiz_limiti', models.PositiveIntegerField(default=5, help_text='Giriş yapmamış veya ücretsiz plandaki kullanıcının günde kaç analiz yapabileceği.', verbose_name='Ücretsiz Günlük Analiz Limiti')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Abonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('deneme', 'Deneme'), ('iptal', 'İptal Edildi')], default='aktif', max_length=10, verbose_name='Durum')),
                ('baslangic', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('bitis', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş (null=Sınırsız)')),
                ('iyzico_odeme_id', models.CharField(blank=True, max_length=100, verbose_name='İyzico Ödeme ID')),
                ('notlar', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonelik', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quant_app.abonelikplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelikler',
            },
        ),
        migrations.CreateModel(
            name='GunlukAnaliz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('adet', models.PositiveIntegerField(default=0, verbose_name='Analiz Sayısı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_analizler', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı (null=anonim)')),
            ],
            options={
                'verbose_name': 'Günlük Analiz Kullanımı',
                'verbose_name_plural': 'Günlük Analiz Kullanımları',
                'unique_together': {('ip_adresi', 'tarih'), ('user', 'tarih')},
            },
        ),
    ]
