# Generated by Django 6.0.6 on 2026-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0002_quantsignalcache_anlik_cci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantsignalcache',
            name='degisim_24s',
            field=models.FloatField(default=0.0, verbose_name='Periyot Değişimi %'),
        ),
        migrations.AlterField(
            model_name='quantsignalcache',
            name='ensemble_accuracy',
            field=models.FloatField(default=0.0, verbose_name='Model Tarihsel Başarısı %'),
        ),
        migrations.AlterField(
            model_name='quantsignalcache',
            name='grafik_verisi_json',
            field=models.TextField(blank=True, default='', verbose_name='Grafik Listeleri JSON Küpü'),
        ),
        migrations.AlterField(
            model_name='quantsignalcache',
            name='period',
            field=models.CharField(max_length=10, verbose_name='Mum Periyodu (interval)'),
        ),
        migrations.AlterField(
            model_name='quantsignalcache',
            name='sembol',
            field=models.CharField(max_length=20, verbose_name='Varlık Sembolü'),
        ),
        migrations.AlterUniqueTogether(
            name='quantsignalcache',
            unique_together={('sembol', 'pazar', 'period')},
        ),
    ]
