# Generated by Django 6.0.6 on 2026-06-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0002_watchlistitem'),
        ('quant_app', '0003_alter_quantsignalcache_degisim_24s_and_more'),
    ]

    operations = [
    ]
