# Generated by Django 6.0.6 on 2026-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0003_abonelikplan_siteayari_abonelik_gunlukanaliz'),
        ('quant_app', '0004_merge_20260625_1107'),
    ]

    operations = [
    ]
