# Generated by Django 6.0.6 on 2026-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0005_merge_20260704_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunlukanaliz',
            name='lab_analiz_adet',
            field=models.PositiveIntegerField(default=0, verbose_name='Lab ML Analiz Sayısı'),
        ),
        migrations.AddField(
            model_name='gunlukanaliz',
            name='tarama_adet',
            field=models.PositiveIntegerField(default=0, verbose_name='Tarama Sayısı (Market Tarama Sekmesi)'),
        ),
        migrations.AddField(
            model_name='siteayari',
            name='ucretsiz_gunluk_lab_analiz_limiti',
            field=models.PositiveIntegerField(default=3, help_text="Ücretsiz kullanıcının günde kaç kez Laboratuvar'da ağır ML analizi çalıştırabileceği.", verbose_name='Ücretsiz Günlük Laboratuvar Analiz Limiti'),
        ),
        migrations.AddField(
            model_name='siteayari',
            name='ucretsiz_gunluk_tarama_limiti',
            field=models.PositiveIntegerField(default=5, help_text='Ücretsiz kullanıcının günde kaç kez Tarama yapabileceği.', verbose_name='Ücretsiz Günlük Tarama Limiti'),
        ),
        migrations.AddField(
            model_name='siteayari',
            name='ucretsiz_takip_listesi_limiti',
            field=models.PositiveIntegerField(default=5, help_text='Ücretsiz kullanıcının takip listesine ekleyebileceği maksimum varlık sayısı.', verbose_name='Ücretsiz Takip Listesi Limiti'),
        ),
        migrations.AlterField(
            model_name='gunlukanaliz',
            name='adet',
            field=models.PositiveIntegerField(default=0, verbose_name='Analiz Sayısı (Market Analiz Sekmesi)'),
        ),
        migrations.AlterField(
            model_name='siteayari',
            name='ucretsiz_gunluk_analiz_limiti',
            field=models.PositiveIntegerField(default=5, help_text='Giriş yapmamış veya ücretsiz plandaki kullanıcının günde kaç kez Market Analiz sekmesini kullanabileceği.', verbose_name='Ücretsiz Günlük Analiz Limiti (Market)'),
        ),
    ]
