# Generated by Django 6.0.6 on 2026-07-11 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0006_gunlukanaliz_lab_analiz_adet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayari',
            name='ucretsiz_alarm_limiti',
            field=models.PositiveIntegerField(default=3, help_text='Ücretsiz kullanıcının kurabileceği maksimum aktif fiyat alarmı sayısı.', verbose_name='Ücretsiz Alarm Limiti'),
        ),
        migrations.CreateModel(
            name='FiyatAlarmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sembol', models.CharField(max_length=20, verbose_name='Varlık Sembolü')),
                ('pazar', models.CharField(max_length=20, verbose_name='Pazar')),
                ('hedef_fiyat', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Hedef Fiyat')),
                ('yon', models.CharField(choices=[('ustune', 'Üstüne Çıkınca'), ('altina', 'Altına İnince')], max_length=10, verbose_name='Yön')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tetiklendi_mi', models.BooleanField(default=False, verbose_name='Tetiklendi mi')),
                ('goruldu_mu', models.BooleanField(default=False, verbose_name='Görüldü mü (bildirim rozeti için)')),
                ('tetiklenme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tetiklenme Zamanı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyat_alarmlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Fiyat Alarmı',
                'verbose_name_plural': 'Fiyat Alarmları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
