# Generated by Django 6.0.6 on 2026-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_app', '0007_siteayari_ucretsiz_alarm_limiti_fiyatalarmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyatalarmi',
            name='olusturulma_fiyati',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Kurulduğu Andaki Fiyat'),
        ),
    ]
